name: deploy-container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy-aws:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/yvy-admin-ui/latest
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/yvy-admin-ui/latest/index.html"

  deploy-oci:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload to OCI bucket
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: os object bulk-upload --namespace ${NAMESPACE} --bucket-name ${BUCKET_NAME} --src-dir dist --object-prefix yvy-admin-ui/latest/
          private-key: ${{ secrets.OCI_CLI_KEY_BASE64 }}
          fingerprint: ${{ secrets.OCI_CLI_FINGERPRINT }}
          tenancy: ${{ secrets.OCI_CLI_TENANCY }}
          user: ${{ secrets.OCI_CLI_USER }}
          region: ${{ secrets.OCI_CLI_REGION }}
        env:
          NAMESPACE: ${{ secrets.OCI_NAMESPACE }}
          BUCKET_NAME: ${{ secrets.OCI_BUCKET_NAME }}